/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamadesktop.view;
import gamadesktop.Depurador;
import gamadesktop.modelo.to.Perfil;
/**
 *
 * @author andre
 */
public class PerfilJFrame extends javax.swing.JFrame {
    private static final Depurador dep = Depurador.getDepurador();
    /**
     * Creates new form PerfilJFrame
     */
    public PerfilJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   public void colocaPerfil(Perfil c){
       dep.log("Colcoa Perfil "+c+ " no painel");     
   }
   public void inserePerfilLista(Perfil c){
       dep.log("Insere Perfil "+c+ " na lista do painel");    
   }
   public Perfil obterPerfilDigitado(){
       Perfil c = new Perfil("Perfil TESTE");
       dep.log("Obtem cargo "+c+ " digitado no painel");
       return c;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
