/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamadesktop.view;
import gamadesktop.Depurador;
import gamadesktop.modelo.to.Cargo;
import gamadesktop.modelo.to.Perfil;
import gamadesktop.modelo.to.Usuario;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author andre
 */
public class UsuarioJFrame extends javax.swing.JFrame {
    private static final Depurador dep = Depurador.getDepurador();
    private DefaultListModel<Usuario> listaUsuarios = new DefaultListModel<Usuario>();
    private DefaultListModel<Perfil> listaPerfisUsuarios = new DefaultListModel<Perfil>();
    
    /**
     * Creates new form UsuarioJFrame
     */
    public UsuarioJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomejTextField1 = new javax.swing.JTextField();
        cpfjTextField2 = new javax.swing.JTextField();
        dataNasjTextField3 = new javax.swing.JTextField();
        generojTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosjList1 = new javax.swing.JList<Usuario>();
        cargojTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        perfisjList2 = new javax.swing.JList<Perfil>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        perfiljTextField6 = new javax.swing.JTextField();
        inserejButton1 = new javax.swing.JButton();
        removerjButton2 = new javax.swing.JButton();
        abrirEditarCargosjButton3 = new javax.swing.JButton();
        abrirEditarPerfisjButton4 = new javax.swing.JButton();
        alterarjButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        inserePerfiljButton6 = new javax.swing.JButton();
        recuperarUsuariosjButton7 = new javax.swing.JButton();
        buscarjButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DataCadastrojLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CPF:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nascimento:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sexo:");

        nomejTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cpfjTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dataNasjTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dataNasjTextField3.setText("01/01/2000");

        generojTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generojTextField4.setText("X");

        usuariosjList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usuariosjList1.setModel(listaUsuarios);
        usuariosjList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(usuariosjList1);

        cargojTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cargojTextField5.setText("CargoX");

        perfisjList2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perfisjList2.setModel(listaPerfisUsuarios);
        jScrollPane2.setViewportView(perfisjList2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Usuários");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Perfis");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cargo:");

        perfiljTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perfiljTextField6.setText("Px");

        inserejButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inserejButton1.setText("Insere");

        removerjButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removerjButton2.setText("Remover");

        abrirEditarCargosjButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        abrirEditarCargosjButton3.setText("Editar Cargos");

        abrirEditarPerfisjButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        abrirEditarPerfisjButton4.setText("Editar Perfis");

        alterarjButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alterarjButton5.setText("Alterar");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Cadastro de Usuários");

        inserePerfiljButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inserePerfiljButton6.setText("Acrescenta Perfil");

        recuperarUsuariosjButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recuperarUsuariosjButton7.setText("Recuperar Todos");

        buscarjButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscarjButton8.setText("Buscar");
        buscarjButton8.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Data Cadastro:");

        DataCadastrojLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        DataCadastrojLabel10.setText("_____________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inserejButton1)
                        .addGap(18, 18, 18)
                        .addComponent(removerjButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterarjButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarjButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(inserePerfiljButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(perfiljTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataNasjTextField3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generojTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cargojTextField5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DataCadastrojLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomejTextField1)
                                        .addComponent(cpfjTextField2)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(abrirEditarCargosjButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(abrirEditarPerfisjButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(recuperarUsuariosjButton7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                                .addGap(30, 30, 30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(DataCadastrojLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cpfjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dataNasjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(generojTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(cargojTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(abrirEditarCargosjButton3)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inserePerfiljButton6)
                            .addComponent(perfiljTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(abrirEditarPerfisjButton4))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserejButton1)
                    .addComponent(removerjButton2)
                    .addComponent(alterarjButton5)
                    .addComponent(buscarjButton8)
                    .addComponent(recuperarUsuariosjButton7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

   public void colocaUsuario(Usuario u){
       dep.log("Colcoa Usuario "+u+ " no painel");   
       nomejTextField1.setText(u.getNomePessoa());
       cpfjTextField2.setText(u.getCpfPessoa());
       dataNasjTextField3.setText(u.getDataNascimento().toString());
       generojTextField4.setText(u.getSexoPessoa());
       cargojTextField5.setText(u.getCargoUsuario().getNomeCargo());
   }
   public void colocaUsuarioSelecionado(){

       Usuario u = usuariosjList1.getSelectedValue();
       if(u!=null){
            dep.log("JFrame - Usuario selecionado foi: "+u);   
            nomejTextField1.setText(u.getNomePessoa());
            cpfjTextField2.setText(u.getCpfPessoa());
            dataNasjTextField3.setText(u.getDataNascimento());
            generojTextField4.setText(u.getSexoPessoa());
            cargojTextField5.setText(u.getCargoUsuario().getNomeCargo());
            DataCadastrojLabel10.setText(u.getCadastroUsuario().toString()); 
            listaPerfisUsuarios.clear();
            int i=0;
            Iterator<Perfil> it = u.getPerfisUauario().iterator();
            while(it.hasNext()){
                Perfil p = (Perfil) it.next();
                listaPerfisUsuarios.addElement(p);
                dep.log("XXXX Adicionando perfil "+ i++ + "do Usuario "+u+ " na lista do painel"); 
            }  
       }
   }
   public void insereNovoUsuarioLista(Usuario u){
       dep.log("Insere Novo Usuario "+u+ " na lista do painel"); 
       listaUsuarios.addElement(u);
       listaPerfisUsuarios.clear();
       int i=0;
       Iterator<Perfil> it = u.getPerfisUauario().iterator();
       while(it.hasNext()){
           Perfil p = (Perfil) it.next();
           listaPerfisUsuarios.addElement(p);
           dep.log("Adicionando perfil "+ i++ + "do Usuario "+u+ " na lista do painel"); 
       }    
   }
   
   public void insereUsuarioLista(Usuario u){
       dep.log("Insere Usuario "+u+ " na lista do painel"); 
       listaUsuarios.addElement(u);    
   }
   public void limpaListaUsuarios(){
       listaUsuarios.clear();
       listaPerfisUsuarios.clear();
   }
   
   
   
   
   public Usuario obterUsuarioDigitado(){
       
       String nome   = nomejTextField1.getText();
       String cpf    = cpfjTextField2.getText();
       String data   = dataNasjTextField3.getText();
       String gen    = generojTextField4.getText();
       String cargo  = cargojTextField5.getText();
       String perfil = perfiljTextField6.getText();
      
       Usuario u = new Usuario(nome,cpf,data,gen,new Cargo(cargo));
       
       for(int i=0; i < listaPerfisUsuarios.getSize(); i++){
           Perfil p = listaPerfisUsuarios.elementAt(i);
           u.addPerfil(p);
       }       
       dep.log("Obtem Usuario "+u+ " digitado no painel");
       
       return u;
   }
   public void insereListaPerfisUsuario(Perfil p){
       listaPerfisUsuarios.addElement(p);      
   }
   public void insereListaCargos(ArrayList<Cargo> lista){
       dep.log("Inserindo lista de possiveis cargos");
   }
   public void insereListaPerfis(ArrayList<Perfil> lista){
       dep.log("Insere lista de possiveis perfis");
   }
   public Perfil obterPerfilASerInseridoUsuario(){
       dep.log("Colocando novo perfil para usuario ");
       return (new Perfil(perfiljTextField6.getText()));
   }
   
   public void adicionaInsereUsuarioListener(ActionListener l){
       inserejButton1.addActionListener(l);
   }
   public void adicionaRemoveUsuariolListener(ActionListener l){
       removerjButton2.addActionListener(l);
   }
   public void adicionaRecuperaUsuariosListener(ActionListener l){
       recuperarUsuariosjButton7.addActionListener(l);
   }
   public void adiicionaInserePerfilUsuarioListener(ActionListener l){
       inserePerfiljButton6.addActionListener(l);
   }
   
   
   public void adicionaEditarUsuarioListener(ActionListener l){
       alterarjButton5.addActionListener(l);
   }
   public void adicionaAbreEditarCargoListener(ActionListener l){
       abrirEditarCargosjButton3.addActionListener(l);
   }
   public void adicionaAbreEditarPerfilListener(ActionListener l){
       abrirEditarPerfisjButton4.addActionListener(l);
   }
   public void adicionaSelecionaUsuaarioListener(ListSelectionListener l){
       usuariosjList1.addListSelectionListener(l);
   }
   
   
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataCadastrojLabel10;
    private javax.swing.JButton abrirEditarCargosjButton3;
    private javax.swing.JButton abrirEditarPerfisjButton4;
    private javax.swing.JButton alterarjButton5;
    private javax.swing.JButton buscarjButton8;
    private javax.swing.JTextField cargojTextField5;
    private javax.swing.JTextField cpfjTextField2;
    private javax.swing.JTextField dataNasjTextField3;
    private javax.swing.JTextField generojTextField4;
    private javax.swing.JButton inserePerfiljButton6;
    private javax.swing.JButton inserejButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomejTextField1;
    private javax.swing.JTextField perfiljTextField6;
    private javax.swing.JList<Perfil> perfisjList2;
    private javax.swing.JButton recuperarUsuariosjButton7;
    private javax.swing.JButton removerjButton2;
    private javax.swing.JList<Usuario> usuariosjList1;
    // End of variables declaration//GEN-END:variables
}
